FROM node:18-alpine

WORKDIR /app

# Copie des fichiers de dépendances
COPY package*.json ./
COPY packages/frontend/package*.json ./packages/frontend/
COPY packages/shared/package*.json ./packages/shared/

# Installation des dépendances
RUN npm install

# Génération des types partagés
RUN npm run build --workspace=shared

# Port exposé
EXPOSE 3000

# Démarrer en mode développement
CMD ["npm", "run", "dev", "--workspace=frontend"]